Update virtual_ward_clinic_app.py - Refine submission part
Due to when the stream app page is loaded without any data inside the table, the below error is always thrown

>>> NameError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
File "/mount/src/virtual_ward_clinic_app/virtual_ward_clinic_app.py", line 151, in <module>
    status.update(label="❌ กรุณากรอกข้อมูลให้ครบถ้วน", state="error")
    ^^^^^^